#import "@local/evcxr:0.1.0": rust-display, dep

= Inline images from Rust

evcxr's display protocol lets a snippet emit MIME-typed payloads to stdout
wrapped in `EVCXR_BEGIN_CONTENT image/png ... EVCXR_END_CONTENT` markers.
The CLI captures these into binary sidecars; the Typst package's
`rust-display` function renders the PNG inline via Typst's native `image()`.

The producer here is the `evcxr_image` runtime crate, which provides an
`ImageDisplay` impl for `image::ImageBuffer`. Calling `.evcxr_display()`
(or just yielding the buffer as the final expression in the Jupyter
convention) is what triggers the MIME emission.

#dep("image", "0.25")
#dep("evcxr_image", "1.1")

#rust-display(```rust
use evcxr_image::ImageDisplay;

let img = image::ImageBuffer::from_fn(256, 256, |x, y| {
    let dx = x as i32 - 128;
    let dy = y as i32 - 128;
    let d2 = dx * dx + dy * dy;
    if d2 < 100 * 100 {
        image::Rgb([30u8, 144, 255])
    } else {
        image::Rgb([245u8, 245, 245])
    }
});

img.evcxr_display();
```)

The Rust source is hidden by `rust-display` (compare `rust`, which shows
both code and output). For figures in a paper-style document, this is
usually what you want: just the picture, captioned by surrounding Typst.

#figure(
  rust-display(```rust
    use evcxr_image::ImageDisplay;
    image::ImageBuffer::from_fn(64, 64, |x, _| {
        let v = (x * 4) as u8;
        image::Rgb([v, v, v])
    }).evcxr_display();
  ```),
  caption: [A 64-pixel grayscale gradient, generated by Rust at build time.],
)
