#import "@local/evcxr:0.1.0": rust, rust-out, rust-hidden, rust-display, rust-data, dep

#set page(numbering: "1")
#set par(justify: true)

= Rainfall: a five-snippet mini-report

This document is a deliberately small data-analysis report. It is the only
example in the gallery that interleaves multiple snippets each building
on the previous one --- the point is to feel like a real document, not a
demo. Five snippets, in order:

+ load a small dataset (snippet 1, a `Vec<Reading>`),
+ compute summary statistics (snippet 2, a function plus a call),
+ render those statistics as a Typst table (snippet 3, via `rust-data`),
+ draw a sparkline-style chart (snippet 4, via `rust-display`),
+ print a one-paragraph natural-language summary (snippet 5).

Each snippet relies on items committed by the snippets before it. This is
the gallery's most ambitious cross-snippet composition example.

#dep("evcxr_image", "1.1")
#dep("image", "0.25")
#dep("serde_json", "1")

== 1. The data

A week of rainfall measurements, in millimetres, for a fictional weather
station. We define a `Reading` struct and an inline corpus. No output ---
this is setup.

#rust-hidden(```rust
#[derive(Clone, Copy, Debug)]
pub struct Reading {
    pub day: u8,
    pub mm: f64,
}

pub static RAIN: &[Reading] = &[
    Reading { day: 1, mm: 0.0 },
    Reading { day: 2, mm: 2.4 },
    Reading { day: 3, mm: 6.1 },
    Reading { day: 4, mm: 0.8 },
    Reading { day: 5, mm: 11.7 },
    Reading { day: 6, mm: 4.2 },
    Reading { day: 7, mm: 0.0 },
];
```)

== 2. Summary statistics

We define a small `summary` helper and call it. Both the function and the
result are committed: later snippets see `summary` and the binding `stats`.

#rust(```rust
pub struct Summary { pub total: f64, pub mean: f64, pub max: f64, pub wet_days: usize }

pub fn summary(rs: &[Reading]) -> Summary {
    let total: f64 = rs.iter().map(|r| r.mm).sum();
    let max = rs.iter().map(|r| r.mm).fold(f64::NEG_INFINITY, f64::max);
    let wet_days = rs.iter().filter(|r| r.mm > 0.0).count();
    Summary { total, mean: total / rs.len() as f64, max, wet_days }
}

let stats = summary(RAIN);
println!("total={:.1}mm  mean={:.2}mm  max={:.1}mm  wet_days={}",
         stats.total, stats.mean, stats.max, stats.wet_days);
```)

== 3. The same numbers, as a Typst table

`rust-data` runs a snippet whose final expression is serialised to JSON
(or CBOR), drops the bytes into a sidecar, and lets Typst read them back
as a real dictionary via `cbor()` / `json()`. We build a Typst table from
that dictionary.

#let stats = rust-data(```rust
serde_json::json!({
    "total":    stats.total,
    "mean":     stats.mean,
    "max":      stats.max,
    "wet_days": stats.wet_days,
})
```)

#table(
  columns: 2,
  [*Metric*], [*Value*],
  [Total rainfall (mm)],   [#stats.total],
  [Mean per day (mm)],     [#stats.mean],
  [Peak day (mm)],         [#stats.max],
  [Wet days (of 7)],       [#stats.wet_days],
)

== 4. A picture

A tiny bar chart, generated by Rust using the same `RAIN` data the table
just consumed. We render straight to PNG via `evcxr_image`.

#figure(
  rust-display(```rust
    use evcxr_image::ImageDisplay;
    let w = 7 * 24;
    let h = 60;
    let scale = h as f64 / stats.max.max(1.0);
    let img = image::ImageBuffer::from_fn(w, h, |x, y| {
        let day = (x / 24) as usize;
        let bar_h = (RAIN[day].mm * scale) as u32;
        if y >= h as u32 - bar_h {
            image::Rgb([30u8, 144, 255])
        } else {
            image::Rgb([248u8, 248, 248])
        }
    });
    img.evcxr_display();
  ```),
  caption: [Daily rainfall, day 1 (left) to day 7 (right).],
)

== 5. In words

Finally, a snippet that reuses `stats` once more to write a one-sentence
prose summary. Captured stdout becomes flowing body text in the rendered
PDF.

#rust-out(```rust
let dry = 7 - stats.wet_days;
println!(
    "Over the week, {:.1} mm of rain fell across {} wet days, with {} dry. \
     The peak was {:.1} mm on day {}.",
    stats.total,
    stats.wet_days,
    dry,
    stats.max,
    RAIN.iter().max_by(|a, b| a.mm.partial_cmp(&b.mm).unwrap()).unwrap().day,
);
```)

This last snippet depends on snippets 1 and 2 (`RAIN`, `stats`) but not 3
or 4 --- a useful illustration that cross-snippet composition is a graph,
not a chain. The cache key (T-D04) needs to reflect that: editing snippet
3 or 4 should not invalidate snippet 5.
